version: '3.8'

services:

  python-receiver:
    build: ./python-receiver
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./python-receiver:/usr/src/app
    ports:
      - 8000:8000