version: '3.8'

services:

  python-receiver:
    build: ./python-receiver
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./python-receiver:/usr/src/app
    ports:
      - 8000:8000
  python-publisher:
    build: ./python-publisher
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8001
    volumes:
      - ./python-receiver:/usr/src/app
    ports:
      - 8001:8001

  go-subscriber:
    build: ./go-subscriber
    command: ./go-subscriber
    volumes:
      - ./go-subscriber:/usr/src/app
    ports:
      - 8002:8002