name: Trigger deployment of container apps infrastructure

on:
  push:
    branches:
      - main
      - infra
    paths:
    - '.github/**'
    - 'bicep/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
   runs-on: ubuntu-22.04
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Log into Azure
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
       resourceGroupName: dapr-containerapps-rg
       template: bicep/main.bicep
       parameters: bicep/container-apps.json
      #  additionalArguments: "--rollback-on-error"

    - name: Azure CLI cleanup
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear
