name: Trigger deployment of container apps infrastructure
concurrency: 
  group: deployment

on:
  push:
    paths:
    - 'bicep/infra/**'
    - '.github/workflows/deploy-infra.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
   runs-on: ubuntu-22.04
   steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Log into Azure
      uses: azure/login@v1
      with:
       creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: What-If Bicep file
      uses: azure/arm-deploy@v1
      with:
       resourceGroupName: dapr-containerapps-rg
       template: bicep/infra/main.bicep
       parameters: bicep/infra/parameters/container-apps.json
       additionalArguments: "--what-if"

    - name: Approve deployment
      uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: adamkielar

    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
       resourceGroupName: dapr-containerapps-rg
       template: bicep/infra/main.bicep
       parameters: bicep/infra/parameters/container-apps.json
       additionalArguments: "--rollback-on-error"

    - name: Azure CLI cleanup
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear
